version: 2

sources:
  - name: barooders
    tables:
      - name: order
      - name: order_line
      - name: product

models:
  - name: stg_barooders__order
    columns:
      - name: id
        tests:
          - unique
          - not_null
